###### FOR HTML BASICS WE MAKE A FILE BASIC_HTML IN WHICH WE USE SOME BASIC THINGS OF HTML FOR HTML BASIC UNDERSTANDING BECAUSE FOR SCRAPPING WE SHOULD HAVE BASIC UNDERSTANDING OF HTML

In [1]:
# THE WEBSITE WHICH WE WANT TO SCRAP
url = 'http://www.espncricinfo.com/rankings/content/page/211271.html'

In [2]:
# IMPORTING LIBRARIES
from requests import get  #FOR GETTING WEB PAGE THAT WE WANT
from bs4 import BeautifulSoup   # FOR SCRAPPING

In [3]:
# GETTING WEBPAGE FROM THIS WEBSITE
response = get(url)  # we get two things from this status code and text

In [4]:
# getting status code of website
response

In [5]:
# getting text of website
response.text

'\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<!-- hostname: web03, edition-view: espncricinfo-en-pk, country: pk, cluster: pak, created: 2023-04-02 02:31:38 -->\n<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://developers.facebook.com/schema/" >\n<head>\n <script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>\n <meta name="google-site-verification" content="ZxdgH3XglRg0Bsy-Ho2RnO3EE4nRs53FloLS6fkt_nc" />\n <meta\n        name="viewport"\n        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"\n      />\n <title>ICC Cricket Rankings - Current ICC Rankings for Tests, ODIs, T20 Cricket | ESPNcricinfo.com</title>\n <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />\n <meta name="keywords" content="cricket rankings, icc cricket rankings, cricket world ranking, icc records" />\n \n <meta name="description" content="Checkout the comprehensive ICC Cricket Rankings for ✓Tests ✓ODIs ✓T20 ✓Women Cricket Teams only on ESPNcricinfo.com" />\n<!--[if IE 9]>\n<script language="javascript" type="text/javascript">\nfunction fnCreateJumpList(iScenario) {\nfnClearJumpList();\nwindow.external.msSiteModeCreateJumpList("Quick Links")\nwindow.external.msSiteModeAddJumpListItem(\'World Cup Super League\', \'https://www.espncricinfo.com/ci/content/current/series/1227837.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'World Test Championship\', \'https://www.espncricinfo.com/ci/content/current/series/1268315.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'Women\'s Championship\', \'https://www.espncricinfo.com/ci/content/current/series/1308225.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'Bangladesh v Ireland\', \'https://www.espncricinfo.com/ci/content/current/series/1355710.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'New Zealand v Sri Lanka\', \'https://www.espncricinfo.com/ci/content/current/series/1322351.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'South Africa v Netherlands\', \'https://www.espncricinfo.com//content/current//1339573.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'South Africa v West Indies\', \'https://www.espncricinfo.com/ci/content/current/series/1339568.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'IPL 2023\', \'https://www.espncricinfo.com/ci/content/current/series/1345038.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeAddJumpListItem(\'Afghanistan v Pakistan\', \'https://www.espncricinfo.com/ci/content/current/series/1362810.html\', \'https://a.espncdn.com/espncricinfo/favicon.ico\');window.external.msSiteModeShowJumpList();\n}\nfunction fnClearJumpList() {\nwindow.external.msSiteModeClearJumplist();\n}\n</script>\n\n<meta name="msapplication-task" content="name=Live Scores;action-uri=https://www.espncricinfo.com/ci/engine/current/match/scores/live.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>\n<meta name="msapplication-task" content="name=Latest News;action-uri=https://www.espncricinfo.com/ci/content/current/story/news.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>\n<meta name="msapplication-task" content="name=Fixtures;action-uri=https://www.espncricinfo.com/ci/content/current/match/fixtures/index.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>\n<meta name="msapplication-task" content="name=Results;action-uri=https://www.espncricinfo.com/ci/engine/current/match/scores/recent.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>\n<meta name="msapplication-task" content="name=Photos;action-uri=https://www.espncricinfo.com/ci/content/current/image/index.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>\n<meta name="msapplication-task" content="name=Audio/Video;action-uri=https://www.espncricinfo.com/ci/content/video_audio/index.html;icon-uri=https://a.espncdn.com/espncricinfo/favicon.ico"/>\n<script language="javascript" type="text/javascript">\n        fnCreateJumpList(2);\n</script>\n<![endif]-->\n\n\n <meta name="robots" content="index, follow" />\n <meta name="googlebot" content="index, follow" />\n <meta property="og:type" content="article"/>\n <meta property="og:title" content=""/>\n \n <meta property="og:image" content="https://a.espncdn.com/i/espn/espn_logos/espncricinfo.png" />\n <link rel="image_src" href="https://a.espncdn.com/i/espn/espn_logos/espncricinfo.png" />\n\n<link rel="shortcut icon" href="https://a.espncdn.com/espncricinfo/favicon.ico" />\n<link rel="icon" type="image/png" href="https://a.espncdn.com/espncricinfo/favicon.png" />\n<link rel="icon" type="image/gif" href="https://a.espncdn.com/espncricinfo/favicon.gif" />\n<link rel="apple-touch-icon" href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-57x57.min.png" />\n<link rel="apple-touch-icon-precomposed" href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-57x57.min.png">\n<link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-72x72.min.png">\n<link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-114x114.min.png">\n<link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-152x152.min.png">\n\n<script language="javascript"  type="text/javascript">\n    let isApp = false;\n    if (window.CleverTap) {\n        isApp = true;\n    } else if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.clevertap) {\n        isApp = true;\n    }\n\n    window.injectScript = function(src, opts) {\n        (function() {\n        var script = document.createElement("script");\n        script.type = "text/javascript";\n        script.async = false;\n        script.src = src;\n        if(opts && typeof opts.id !== "undefined") script.id = opts.id;\n        if(opts && typeof opts.async !== "undefined") script.async = opts.async;\n        if(opts && typeof opts.defer !== "undefined") script.defer = opts.defer;\n        var s = document.getElementsByTagName(\'script\')[0];\n        s.parentNode.insertBefore(script, s);\n        })();\n    };\n\n    if (!isApp) {\n        \n            window.injectScript(\'https://dcf.espn.com/TWDC-DTCI/prod/Bootstrap.js\');\n        \n    }\n</script>\n\n<meta property="fb:app_id" content="260890547115" />\n<meta property="og:site_name" content="Cricinfo" />\n\n\n\n <meta property="og:title" content=""/>\n\n <!-- Cricinfo Global News RSS feed link -->\n<link href="/rss/content/story/feeds/0.xml" rel="alternate" type="application/rss+xml" title="Global News RSS Feed" />\n<link href="/rss/livescores.xml" rel="alternate" type="application/rss+xml" title="Cricinfo live scores RSS feed" />\n\n\n<link rel="stylesheet" href="https://a.espncdn.com/combiner/c?css=fonts/bentonsans.css,fonts/bentonsansbold.css,fonts/bentonsanslight.css,fonts/bentonsansmedium.css,fonts/bentonsanscond.css,fonts/bentonsanscondbold.css,fonts/bentonsanscondmedium.css" type="text/css" media="screen" charset="utf-8">\n<link rel="stylesheet" href="https://i.imgci.com/navigation/cricinfo/ci/assets/css/main_nav.css?v=1616584657" type="text/css" media="screen" charset="utf-8">\n<link rel="stylesheet" href="https://i.imgci.com/navigation/cricinfo/ci/assets/css/sub_nav.css?v=1616584657" type="text/css" media="screen" charset="utf-8">\n<link rel="stylesheet" type="text/css" href="https://i.imgci.com/navigation/cricinfo/ci/global.0.0.1.css?1602154871"/>\n\n<script language="javascript" type="text/javascript">\n\tif(navigator.userAgent.indexOf(\'Linux\') != -1) { \n\t\tvar linux = \'/navigation/cricinfo/ci/global_linux.css?1602154873\';\n\t\tvar linuxcss=document.createElement("link");\n\t\tlinuxcss.setAttribute("rel", "stylesheet");\n\t\tlinuxcss.setAttribute("type", "text/css");\n\t\tlinuxcss.setAttribute("href", linux);\n\t\tdocument.getElementsByTagName("head")[0].appendChild(linuxcss);\n\t}\n</script>\n\n <script language="javascript" type="text/javascript" src="https://i.imgci.com/navigation/cricinfo/ci/jquery-1.7.2.min.js"></script>\n <script language="javascript" type="text/javascript" src="https://i.imgci.com/navigation/cricinfo/ci/default.js?1671195368"></script>\n\n<script src="https://a.espncdn.com/combiner/c?js=jquery-1.7.1.js,plugins/jquery.metadata.js,plugins/jquery.pubsub.r5.js,plugins/ba-debug-0.4.js,espn.l10n.r12.js,espn.core.duo.r55.js,espn.storage.r6.js,espn.geo.r2.js"></script>\n\n<link rel="stylesheet" href="https://a.espncdn.com/players/web-player-bundle/3.2.13/espn-web-player-bundle.css" />\n<!-- VOD Shim starts -->\n\n<script src="https://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery-2.0.2.min.js"></script>\n<script src="https://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery.cookie-1.4.1.min.js"></script>\n<script src="https://a.espncdn.com/players/web-player-bundle/3.2.38/espn-web-player-bundle.min.js"></script>\n<script src="https://i.imgci.com/navigation/cricinfo/ci/videoplayer/dtciplayer.js"></script>\n<!-- VOD Shim ends -->\n\n\n\n<script language="javascript"  type="text/javascript">\n\tif (typeof $ === \'undefined\'){\t\n\t\tvar $ = jQuery;\n\t}\n\tord=Math.random()*10000000000000000;\n\tvar ad_counter = 1;\n\n\tcqanswer = \'pk\';\n\tlocation_country = \'pk\';\n\tlocation_cluster = \'pak\';\n</script>\n\n<script src="https://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery.cookie-1.4.1.min.js"></script>\n\n<style type="text/css">\n.video-play-button{background: url(https://i.imgci.com/espncricinfo/video/play-icon.png) no-repeat left bottom;bottom: 10px;left: 10px;position: absolute;right: 0px;text-shadow: none;top: 0px;width: 100%;background-size: 50px auto;opacity: .6;color: transparent;cursor:pointer;}\n.video-play-button:hover{opacity: 1;}\n</style>\n\n<meta name="application-name" content="ESPNcricinfo"/>\n<meta name="msapplication-TileColor" content="#266ab4"/>\n<meta name="msapplication-TileImage" content="https://i.imgci.com/espncricinfo/6b245241-3938-499c-8c79-9b80f97bed96.png"/>\n\n\n\r\n<script type=\'text/javascript\'>\r\n  window.s_account = "wdgespcricinfo,wdgespge";\r\n  \r\n</script>\r\n\r\n<!-- Load GPT JavaScript library used by DFP -->\r\n<script type="text/javascript">\r\n  var googletag = googletag || {};\r\n  googletag.cmd = googletag.cmd || [];\r\n  (function() {\r\n    var gads = document.createElement("script");\r\n    gads.async = true;\r\n    gads.type = "text/javascript";\r\n    var useSSL = true;\r\n    // var useSSL = "https:" == document.location.protocol;\r\n    gads.src = (useSSL ? "https:" : "http:") + "//www.googletagservices.com/tag/js/gpt.js";\r\n    var node =document.getElementsByTagName("script")[0];\r\n    node.parentNode.insertBefore(gads, node);\r\n   })();\r\n</script>\r\n<script type="text/javascript" src="https://a.espncdn.com/combiner/c?js=swfobject/2.2/swfobject.js?minify=false"></script>\r\n\n\r\n<style>\r\n.espni-ad-slot{line-height: 0;}\r\npre.gpt-debug{padding: 10px; background: burlywood;}\r\n</style>\r\n\r\n  <script type=\'text/javascript\'> \r\n  var ad_setting = {"adtar":"","kvbrand":"rankings","kvcluster":"pak","kvnavtype":"","kvpt":"index","kvsite":"","kvstoryid":"211271","networkid":"21783347309","path":"/21783347309/espn.cricinfo.com/others","sp":"cricinfo","template":"desktop","template_type":"non_responsive","tstAdTar":""}; var __GPTenabled = true; \r\n  window.espn = window.espn || {};\r\n  window.espn.ads = window.espn.ads || {};\r\n  window.espn.ads.config = window.espn.ads.config || {};\r\n  window.espn.ads.config.level = "espn.cricinfo.com/others";\r\n  </script>\r\n\r\n<style>.vjs-logolink.hide{display:none;}</style>\r\n\n</head>\n<body\n\n id="cric_old_template">\n\n\n\n\n<section class="mainnav_wrap" id="mainnav_wrap">\n\t<div class="nav_inner" id="nav_inner">\n\n\t\t<div class="nav_btn" id="nav_btn">\n\t\t\t<span class="back-icon-svg">\n\t\t\t\t<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 31.494 31.494" style="enable-background:new 0 0 31.494 31.494;" xml:space="preserve"> <path style="fill:#FFFFFF;" d="M10.273,5.009c0.444-0.444,1.143-0.444,1.587,0c0.429,0.429,0.429,1.143,0,1.571l-8.047,8.047h26.554 c0.619,0,1.127,0.492,1.127,1.111c0,0.619-0.508,1.127-1.127,1.127H3.813l8.047,8.032c0.429,0.444,0.429,1.159,0,1.587 c-0.444,0.444-1.143,0.444-1.587,0l-9.952-9.952c-0.429-0.429-0.429-1.143,0-1.571L10.273,5.009z"/> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </svg>\n\t\t\t</span>\n\t\t</div>\n\n\t\t<div class="ci_logo" id="ci_logo">\n\t\t\t\n\t\t\t<a href="/">\n\t\t\t\n\t\t\t\t \n\t\t\t\t <img src="https://www.espncricinfo.com/static/images/logo.png">\n\t\t\t\t \n\t\t\t\t<span class="logo_txt">ESPN Cricinfo</span>\n\t\t\t</a>\n\t\t</div>\n\n\t\t<nav class="main_nav" id="main_nav" data-role="none">\n\n\n\t\t\t<ul class="nav_grp" id="nav_grp" data-role="none">\n\n\t\t\t\t\t\t\t<li class="nav_grpitm nav_live_scores">\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<a href="/live-cricket-score" name="&lpos=header_livescores">Live Scores</a>\n\n\t\t\t\t\t\t\t\t<div class="nav_grp_lvl1 main_nav_options dd_wrap">\n\n\t\t\t\t\t\t\t\t\t<ul class="sub_nav" data-role="none">\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/live-cricket-score" name="&lpos=header_livescores">Live Scores Home</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/live-cricket-match-schedule-fixtures" name="&lpos=header_livescores">Schedule</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/live-cricket-match-results" name="&lpos=header_livescores">Results</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/engine/series/index.html?view=month" name="&lpos=header_livescores">Month view</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/engine/series/index.html?view=season" name="&lpos=header_livescores">Season view</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/engine/match/index.html?view=calendar" name="&lpos=header_livescores">International calendar</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/engine/match/scores/desktop.html" name="&lpos=header_livescores">Desktop Scoreboard</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t</ul>\n\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t<li class="nav_grpitm nav_series">\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/content/match/fixtures_futures.html" name="&lpos=header_series">Series</a>\n\n\t\t\t\t\t\t\t\t<div class="nav_grp_lvl1 main_nav_options dd_wrap">\n\n\t\t\t\t\t\t\t\t\t<ul class="sub_nav" data-role="none">\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/indian-premier-league-2023-1345038" name="&lpos=header_series">IPL 2023</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/afghanistan-v-pakistan-2022-23-1362810" name="&lpos=header_series">Afghanistan v Pakistan</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/sri-lanka-tour-of-new-zealand-2022-23-1322351" name="&lpos=header_series">New Zealand v Sri Lanka</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/ireland-in-bangladesh-2022-23-1355710" name="&lpos=header_series">Bangladesh v Ireland</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/netherlands-in-south-africa-2021-22-2022-23-1277056" name="&lpos=header_series">South Africa v Netherlands</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/fairbreak-invitational-tournament-2023-1366009" name="&lpos=header_series">FairBreak T20</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/icc-world-test-championship-2021-2023-1268315" name="&lpos=header_series">Test Championship</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/icc-women-s-championship-2022-23-2025-1308225" name="&lpos=header_series">Women\'s Championship</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/world-cup-super-league-2020-2022-23-1227837" name="&lpos=header_series">CWC Super League</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/world-cup-league-2-2019-2021-22-1196667" name="&lpos=header_series">CWC League 2</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/pakistan-cup-2022-23-1349045/match-schedule-fixtures-and-results" name="&lpos=header_series">Pakistan Cup</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="/series/cricket-associations-challenge-2022-23-1349396/match-schedule-fixtures-and-results" name="&lpos=header_series">PCB Challenge</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/content/match/fixtures_futures.html" name="&lpos=header_series">-Future series-</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t<a href="https://www.espncricinfo.com/ci/engine/series/index.html" name="&lpos=header_series">-Archives-</a>\n\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t</ul>\n\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t<li class="nav_grpitm nav_teams">\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<a href="/team" name="&lpos=header_teams">Teams</a>\n\n\t\t\t\t\t\t\t\t<div class="nav_grp_lvl1 main_nav_options dd_wrap">\n\n\t\t\t\t\t\t\t\t\t<ul class="subnav_grp" data-role="none">\n\n\t\t\t\t\t\t\t\t\t\t<li class="subnav_grpitm">\n\n\t\t\t\t\t\t\t\t\t\t\t<ul class="sub_nav" data-role="none">\n\n\t\t\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<a href="/team/australia-2" name="&lpos=header_teams">Australia</a>\n\t\t\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<a href="/team/afghanistan-40" name="&lpos=header_teams">Afghanistan</a>\n\t\t\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<a href="/team/bangladesh-25" name="&lpos=header_teams">Bangladesh</a>\n\t\t\t\t\t\t\t\t\t\t\t\t</li>\n\n\t\t\t\t\t\t\t\t\t\t\t\t<li class="sub_nav_item">\n\t\t\

In [6]:
# parsing the text of html in beautiful soup
html_soup = BeautifulSoup(response.text, 'html.parser')

In [7]:
ranking = html_soup.find_all('table', class_ = 'StoryengineTable')

In [8]:
#Lets explore a bit

In [9]:
len(ranking)# we have 5 tables

5

In [10]:
ranking # we print all tables

[<table class="StoryengineTable">
 <caption>20 March 2023</caption>
 <tr class="head">
 <th class="left">Pos</th>
 <th class="left">Team</th>
 <th class="left">Matches</th>
 <th class="left">Points</th>
 <th class="left">Rating</th>
 </tr>
 <tr>
 <td class="left">1</td>
 <td class="left">Australia</td>
 <td class="left">34</td>
 <td class="left">4143</td>
 <td class="left">122</td>
 </tr>
 <tr>
 <td class="left">2</td>
 <td class="left">India</td>
 <td class="left">37</td>
 <td class="left">4420</td>
 <td class="left">119</td>
 </tr>
 <tr>
 <td class="left">3</td>
 <td class="left">England</td>
 <td class="left">47</td>
 <td class="left">5017</td>
 <td class="left">107</td>
 </tr>
 <tr>
 <td class="left">4</td>
 <td class="left">South Africa</td>
 <td class="left">32</td>
 <td class="left">3336</td>
 <td class="left">104</td>
 </tr>
 <tr>
 <td class="left">5</td>
 <td class="left">New Zealand</td>
 <td class="left">33</td>
 <td class="left">3379</td>
 <td class="left">102</td>
 </tr>
 <tr>
 <td class="left">6</td>
 <td class="left">Pakistan</td>
 <td class="left">30</td>
 <td class="left">2638</td>
 <td class="left">88</td>
 </tr>
 <tr>
 <td class="left">7</td>
 <td class="left">Sri Lanka</td>
 <td class="left">29</td>
 <td class="left">2429</td>
 <td class="left">84</td>
 </tr>
 <tr>
 <td class="left">8</td>
 <td class="left">West Indies</td>
 <td class="left">34</td>
 <td class="left">2571</td>
 <td class="left">76</td>
 </tr>
 <tr>
 <td class="left">9</td>
 <td class="left">Bangladesh</td>
 <td class="left">25</td>
 <td class="left">1161</td>
 <td class="left">46</td>
 </tr>
 <tr>
 <td class="left">10</td>
 <td class="left">Zimbabwe</td>
 <td class="left">9</td>
 <td class="left">243</td>
 <td class="left">27</td>
 </tr>
 </table>,
 <table class="StoryengineTable">
 <caption>29 March 2023</caption>
 <tr class="head">
 <th class="left">Pos</th>
 <th class="left">Team</th>
 <th class="left">Matches</th>
 <th class="left">Points</th>
 <th class="left">Rating</th>
 </tr>
 <tr>
 <td class="left">1</td>
 <td class="left">Australia</td>
 <td class="left">35</td>
 <td class="left">3965</td>
 <td class="left">113</td>
 </tr>
 <tr>
 <td class="left">2</td>
 <td class="left">India</td>
 <td class="left">47</td>
 <td class="left">5294</td>
 <td class="left">113</td>
 </tr>
 <tr>
 <td class="left">3</td>
 <td class="left">New Zealand</td>
 <td class="left">30</td>
 <td class="left">3367</td>
 <td class="left">112</td>
 </tr>
 <tr>
 <td class="left">4</td>
 <td class="left">England</td>
 <td class="left">36</td>
 <td class="left">3988</td>
 <td class="left">111</td>
 </tr>
 <tr>
 <td class="left">5</td>
 <td class="left">Pakistan</td>
 <td class="left">25</td>
 <td class="left">2649</td>
 <td class="left">106</td>
 </tr>
 <tr>
 <td class="left">6</td>
 <td class="left">South Africa</td>
 <td class="left">29</td>
 <td class="left">2919</td>
 <td class="left">101</td>
 </tr>
 <tr>
 <td class="left">7</td>
 <td class="left">Bangladesh</td>
 <td class="left">38</td>
 <td class="left">3625</td>
 <td class="left">95</td>
 </tr>
 <tr>
 <td class="left">8</td>
 <td class="left">Sri Lanka</td>
 <td class="left">35</td>
 <td class="left">3037</td>
 <td class="left">87</td>
 </tr>
 <tr>
 <td class="left">9</td>
 <td class="left">West Indies</td>
 <td class="left">43</td>
 <td class="left">3105</td>
 <td class="left">72</td>
 </tr>
 <tr>
 <td class="left">10</td>
 <td class="left">Afghanistan</td>
 <td class="left">20</td>
 <td class="left">1419</td>
 <td class="left">71</td>
 </tr>
 <tr>
 <td class="left">11</td>
 <td class="left">Ireland</td>
 <td class="left">27</td>
 <td class="left">1384</td>
 <td class="left">51</td>
 </tr>
 <tr>
 <td class="left">12</td>
 <td class="left">Scotland</td>
 <td class="left">35</td>
 <td class="left">1567</td>
 <td class="left">45</td>
 </tr>
 <tr>
 <td class="left">13</td>
 <td class="left">Zimbabwe</td>
 <td class="left">31</td>
 <td class="left">1351</td>
 <td class="left">44</td>
 </tr>
 <tr>
 <td class="left">14</td>
 <td class="left">Netherlands</td>
 <td class="left">24</td>
 <td class="left">749</td>
 <td class="left">31</td>
 </tr>
 <tr>
 <td class="left">15</td>
 <td class="left">Nepal</td>
 <td class="left">40</td>
 <td class="left">1238</td>
 <td class="left">31</td>
 </tr>
 <tr>
 <td class="left">16</td>
 <td class="left">Oman</td>
 <td class="left">30</td>
 <td class="left">919</td>
 <td class="left">31</td>
 </tr>
 <tr>
 <td class="left">17</td>
 <td class="left">Namibia</td>
 <td class="left">34</td>
 <td class="left">990</td>
 <td class="left">29</td>
 </tr>
 <tr>
 <td class="left">18</td>
 <td class="left">USA</td>
 <td class="left">33</td>
 <td class="left">901</td>
 <td class="left">27</td>
 </tr>
 <tr>
 <td class="left">19</td>
 <td class="left">UAE</td>
 <td class="left">36</td>
 <td class="left">739</td>
 <td class="left">21</td>
 </tr>
 <tr>
 <td class="left">20</td>
 <td class="left">PNG</td>
 <td class="left">40</td>
 <td class="left">181</td>
 <td class="left">5</td>
 </tr>
 </table>,
 <table class="StoryengineTable">
 <caption>29 March 2023</caption>
 <tr class="head">
 <th class="left">Pos</th>
 <th class="left">Team</th>
 <th class="left">Matches</th>
 <th class="left">Points</th>
 <th class="left">Rating</th>
 </tr>
 <tr>
 <td class="left">1</td>
 <td class="left">India</td>
 <td class="left">69</td>
 <td class="left">18445</td>
 <td class="left">267</td>
 </tr>
 <tr>
 <td class="left">2</td>
 <td class="left">England</td>
 <td class="left">52</td>
 <td class="left">13555</td>
 <td class="left">261</td>
 </tr>
 <tr>
 <td class="left">3</td>
 <td class="left">Pakistan</td>
 <td class="left">58</td>
 <td class="left">14775</td>
 <td class="left">255</td>
 </tr>
 <tr>
 <td class="left">4</td>
 <td class="left">South Africa</td>
 <td class="left">44</td>
 <td class="left">11170</td>
 <td class="left">254</td>
 </tr>
 <tr>
 <td class="left">5</td>
 <td class="left">New Zealand</td>
 <td class="left">53</td>
 <td class="left">13371</td>
 <td class="left">252</td>
 </tr>
 <tr>
 <td class="left">6</td>
 <td class="left">Australia</td>
 <td class="left">47</td>
 <td class="left">11784</td>
 <td class="left">251</td>
 </tr>
 <tr>
 <td class="left">7</td>
 <td class="left">West Indies</td>
 <td class="left">54</td>
 <td class="left">12855</td>
 <td class="left">238</td>
 </tr>
 <tr>
 <td class="left">8</td>
 <td class="left">Sri Lanka</td>
 <td class="left">53</td>
 <td class="left">12485</td>
 <td class="left">236</td>
 </tr>
 <tr>
 <td class="left">9</td>
 <td class="left">Bangladesh</td>
 <td class="left">56</td>
 <td class="left">12746</td>
 <td class="left">228</td>
 </tr>
 <tr>
 <td class="left">10</td>
 <td class="left">Afghanistan</td>
 <td class="left">36</td>
 <td class="left">7928</td>
 <td class="left">220</td>
 </tr>
 <tr>
 <td class="left">11</td>
 <td class="left">Zimbabwe</td>
 <td class="left">49</td>
 <td class="left">9597</td>
 <td class="left">196</td>
 </tr>
 <tr>
 <td class="left">12</td>
 <td class="left">Ireland</td>
 <td class="left">59</td>
 <td class="left">11172</td>
 <td class="left">189</td>
 </tr>
 <tr>
 <td class="left">13</td>
 <td class="left">UAE</td>
 <td class="left">32</td>
 <td class="left">5898</td>
 <td class="left">184</td>
 </tr>
 <tr>
 <td class="left">14</td>
 <td class="left">Namibia</td>
 <td class="left">32</td>
 <td class="left">5846</td>
 <td class="left">183</td>
 </tr>
 <tr>
 <td class="left">15</td>
 <td class="left">Scotland</td>
 <td class="left">24</td>
 <td class="left">4373</td>
 <td class="left">182</td>
 </tr>
 <tr>
 <td class="left">16</td>
 <td class="left">Nepal</td>
 <td class="left">30</td>
 <td class="left">5387</td>
 <td class="left">180</td>
 </tr>
 <tr>
 <td class="left">17</td>
 <td class="left">Netherlands</td>
 <td class="left">32</td>
 <td class="left">5668</td>
 <td class="left">177</td>
 </tr>
 <tr>
 <td class="left">18</td>
 <td class="left">Oman</td>
 <td class="left">26</td>
 <td class="left">4090</td>
 <td class="left">157</td>
 </tr>
 <tr>
 <td class="left">19</td>
 <td class="left">PNG</td>
 <td class="left">24</td>
 <td class="left">3495</td>
 <td class="left">146</td>
 </tr>
 <tr>
 <td class="left">20</td>
 <td class="left">Canada</td>
 <td class="left">24</td>
 <td class="left">3297</td>
 <td class="left">137</td>
 </tr>
 <tr>
 <td class="left">21</td>
 <td class="left">Hong Kong</td>
 <td class="left">24</td>
 <td class="left">3205</td>
 <td class="left">134</td>
 </tr>
 <tr>
 <td class="left">22</td>
 <td class="left">Qatar</td>
 <td class="left">17</td>
 <td class="left">2169</td>
 <td class="left">128</td>
 </tr>
 <tr>
 <td class="left">23</td>
 <td class="left">Jersey</td>
 <td class="left">23</td>
 <td class="left">2924</td>
 <td class="left">127</td>
 </tr>
 <tr>
 <td class="left">24</td>
 <td class="left">Uganda</td>
 <td class="left">46</td>
 <td class="left">5648</td>
 <td class="left">123</td>
 </tr>
 <tr>
 <td class="left">25</td>
 <td class="left">USA</td>
 <td class="left">16</td>
 <td class="left">1908</td>
 <td class="left">119</td>
 </tr>
 <tr>
 <td class="left">26</td>
 <td class="left">Kuwait</td>
 <td class="left">22</td>
 <td class="left">2501</td>
 <td class="left">114</td>
 </tr>
 <tr>
 <td class="left">27</td>
 <td class="left">Malaysia</td>
 <td class="left">37</td>
 <td class="left">4139</td>
 <td class="left">112</td>
 </tr>
 <tr>
 <td class="left">28</td>
 <td class="left">Kenya</td>
 <td class="left">31</td>
 <td class="left">3272</td>
 <td class="left">106</td>
 </tr>
 <tr>
 <td class="left">29</td>
 <td class="left">Bahrain</td>
 <td class="left">33</td>
 <td class="left">3435</td>
 <td class="left">104</td>
 </tr>
 <tr>
 <td class="left">30</td>
 <td class="left">Singapore</td>
 <td class="left">28</td>
 <td class="left">2861</td>
 <td class="left">102</td>
 </tr>
 <tr>
 <td class="left">31</td>
 <td class="left">Tanzania</td>
 <td class="left">36</td>
 <td class="left">3598</td>
 <td class="left">100</td>
 </tr>
 <tr>
 <td class="left">32</td>
 <td class="left">Italy</td>
 <td class="left">19</td>
 <td class="left">1818</td>
 <td class="left">96</td>
 </tr>
 <tr>
 <td class="left">33</td>
 <td class="left">Saudi Arabia</td>
 <td class="left">13</td>
 <td class="left">1234</td>
 <td class="left">95</td>
 </tr>
 <tr>
 <td class="left">34</td>
 <td class="left">Bermuda</td>
 <td class="left">18</td>
 <td class="left">1671</td>
 <td class="left">93</td>
 </tr>
 <tr>
 <td class="left">35</td>
 <td class="left">Germany</td>
 <td class="left">34</td>
 <td class="left">2996</td>
 <td class="left">88</td>
 </tr>
 <tr>
 <td class="left">36</td>
 <td class="left">Spain</td>
 <td class="left">26</td>
 <td class="left">2267</td>
 <td class="left">87</td>
 </tr>
 <tr>
 <td class="left">37</td>
 <td class="left">Denmark</td>
 <td class="left">21</td>
 <td class="left">1518</td>
 <td class="left">72</td>
 </tr>
 <tr>
 <td class="left">38</td>
 <td class="left">Guernsey</td>
 <td class="left">17</td>
 <td class="left">1194</td>
 <td class="left">70</td>
 </tr>
 <tr>
 <td class="left">39</td>
 <td class="left">Cayman Islands</td>
 <td class="left">12</td>
 <td class="left">814</td>
 <td class="left">68</td>
 </tr>
 <tr>
 <td class="left">40</td>
 <td class="left">Belgium</td>
 <td class="left">20</td>
 <td class="left">1349</td>
 <td class="left">67</td>
 </tr>
 <tr>
 <td class="left">41</td>
 <td class="left">Nigeria</td>
 <td class="left">29</td>
 <td class="left">1952</td>
 <td class="left">67</td>
 </tr>
 <tr>
 <td class="left">42</td>
 <td class="left">Austria</td>
 <td class="left">26</td>
 <td class="left">1686</td>
 <td class="left">65</td>
 </tr>
 <tr>
 <td class="left">43</td>
 <td class="left">Vanuatu</td>
 <td class="left">14</td>
 <td class="left">877</td>
 <td class="left">63</td>
 </tr>
 <tr>
 <td class="left">44</td>
 <td class="left">Portugal</td>
 <td class="left">11</td>
 <td class="left">644</td>
 <td class="left">59</td>
 </tr>
 <tr>
 <td class="left">45</td>
 <td class="left">Romania</td>
 <td class="left">24</td>
 <td class="left">1359</td>
 <td class="left">57</td>
 </tr>
 <tr>
 <td class="left">46</td>
 <td class="left">Isle of Man</td>
 <td class="left">15</td>
 <td class="left">847</td>
 <td class="left">56</td>
 </tr>
 <tr>
 <td class="left">47</td>
 <td class="left">Botswana</td>
 <td class="left">18</td>
 <td class="left">992</td>
 <td class="left">55</td>
 </tr>
 <tr>
 <td class="left">48</td>
 <td class="left">Norway</td>
 <td class="left">17</td>
 <td class="left">897</td>
 <td class="left">53</td>
 </tr>
 <tr>
 <td class="left">49</td>
 <td class="left">Finland</td>
 <td class="left">17</td>
 <td class="left">892</td>
 <td class="left">52</td>
 </tr>
 <tr>
 <td class="left">50</td>
 <td class="left">France</td>
 <td class="left">9</td>
 <td class="left">470</td>
 <td class="left">52</td>
 </tr>
 <tr>
 <td class="left">51</td>
 <td class="left">Malawi</td>
 <td class="left">17</td>
 <td class="left">818</td>
 <td class="left">48</td>
 </tr>
 <tr>
 <td class="left">52</td>
 <td class="left">Sweden</td>
 <td class="left">16</td>
 <td class="left">690</td>
 <td class="left">43</td>
 </tr>
 <tr>
 <td class="left">53</td>
 <td class="left">Cook Islands</td>
 <td class="left">6</td>
 <td class="left">245</td>
 <td class="left">41</td>
 </tr>
 <tr>
 <td class="left">54</td>
 <td class="left">Czech Republic</td>
 <td class="left">28</td>
 <td class="left">1137</td>
 <td class="left">41</td>
 </tr>
 <tr>
 <td class="left">55</td>
 <td class="left">Argentina</td>
 <td class="left">15</td>
 <td class="left">604</td>
 <td class="left">40</td>
 </tr>
 <tr>
 <td class="left">56</td>
 <td class="left">Indonesia</td>
 <td class="left">7</td>
 <td class="left">265</td>
 <td class="left">38</td>
 </tr>
 <tr>
 <td class="left">57</td>
 <td class="left">Switzerland</td>
 <td class="left">11</td>
 <td class="left">396</td>
 <td class="left">36</td>
 </tr>
 <tr>
 <td class="left">58</td>
 <td class="left">Malta</td>
 <td class="left">33</td>
 <td class="left">1179</td>
 <td class="left">36</td>
 </tr>
 <tr>
 <td class="left">59</td>
 <td class="left">Ghana</td>
 <td class="left">23</td>
 <td class="left">813</td>
 <td class="left">35</td>
 </tr>
 <tr>
 <td class="left">60</td>
 <td class="left">Sierra Leone</td>
 <td class="left">17</td>
 <td class="left">586</td>
 <td class="left">34</td>
 </tr>
 <tr>
 <td class="left">61</td>
 <td class="left">Japan</td>
 <td class="left">7</td>
 <td class="left">236</td>
 <td class="left">34</td>
 </tr>
 <tr>
 <td class="left">62</td>
 <td class="left">Luxembourg</td>
 <td class="left">23</td>
 <td class="left">774</td>
 <td class="left">34</td>
 </tr>
 <tr>
 <td class="left">63</td>
 <td class="left">Mozambique</td>
 <td class="left">23</td>
 <td class="left">721</td>
 <td class="left">31</td>
 </tr>
 <tr>
 <td class="left">64</td>
 <td class="left">Fiji</td>
 <td class="left">10</td>
 <td class="left">304</td>
 <td class="left">30</td>
 </tr>
 <tr>
 <td class="left">65</td>
 <td class="left">Bhutan</td>
 <td class="left">8</td>
 <td class="left">239</td>
 <td class="left">30</td>
 </tr>
 <tr>
 <td class="left">66</td>
 <td class="left">Rwanda</td>
 <td class="left">34</td>
 <td class="left">918</td>
 <td class="left">27</td>
 </tr>
 <tr>
 <td class="left">67</td>
 <td class="left">Cyprus</td>
 <td class="left">11</td>
 <td class="left">283</td>
 <td class="left">26</td>
 </tr>
 <tr>
 <td class="left">68</td>
 <td class="left">Bahamas</td>
 <td class="left">15</td>
 <td class="left">359</td>
 <td class="left">24</td>
 </tr>
 <tr>
 <td class="left">69</td>
 <td class="left">Hungary</td>
 <td class="left">16</td>
 <td class="left">358</td>
 <td class="left">22</td>
 </tr>
 <tr>
 <td class="left">70</td>
 <td class="left">Panama</td>
 <td class="left">10</td>
 <td class="left">222</td>
 <td class="left">22</td>
 </tr>
 <tr>
 <td class="left">71</td>
 <td class="left">Belize</td>
 <td class="left">6</td>
 <td class="left">132</td>
 <td class="left">22</td>
 </tr>
 <tr>
 <td class="left">72</td>
 <td class="left">Serbia</td>
 <td class="left">17</td>
 <td class="left">184</td>
 <td class="left">11</td>
 </tr>
 <tr>
 <td class="left">73</td>
 <td class="left">Bulgaria</td>
 <td class="left">34</td>
 <td class="left">296</td>
 <td class="left">9</td>
 </tr>
 <tr>
 <td class="left">74</td>
 <td class="left">Gambia</td>
 <td class="left">7</td>
 <td class="left">50</td>
 <td class="left">7</td>
 </tr>
 <tr>
 <td class="left">75</td>
 <td class="left">Lesotho</td>
 <td class="left">12</td>
 <td class="left">82</td>
 <td class="left">7</td>
 </tr>
 <tr>
 <td class="left">76</td>
 <td class="left">Maldives</td>
 <td class="left">15</td>
 <td class="left">81</td>
 <td class="left">5</td>
 </tr>
 <tr>
 <td class="left">77</td>
 <td class="left">Gibraltar</td>
 <td class="left">21</td>
 <td class="left">68</td>
 <td class="left">3</td>
 </tr>
 <tr>
 <td class="left">78</td>
 <td class="left">Greece</td>
 <td class="left">9</td>
 <td class="left">27</td>
 <td class="left">3</td>
 </tr>
 <tr>
 <td class="left">79</td>
 <td class="left">Turkey</td>
 <td class="left">6</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 <tr>
 <td class="left">80</td>
 <td class="left">Thailand</td>
 <td class="left">10</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 <tr>
 <td class="left">81</td>
 <td class="left">Eswatini</td>
 <td class="left">18</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 <tr>
 <td class="left">82</td>
 <td class="left">Seychelles</td>
 <td class="left">10</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 <tr>
 <td class="left">83</td>
 <td class="left">Samoa</td>
 <td class="left">11</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 <tr>
 <td class="left">84</td>
 <td class="left">Estonia</td>
 <td class="left">12</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 <tr>
 <td class="left">85</td>
 <td class="left">Cameroon</td>
 <td class="left">13</td>
 <td class="left">0</td>
 <td class="left">0</td>
 </tr>
 </table>,
 <table class="StoryengineTable">
 <caption>21 January 2023</caption>
 <tr class="head">
 <th class="left">Pos</th>
 <th class="left">Team</th>
 <th class="left">Matches</th>
 <th class="left">Points</th>
 <th class="left">Rating</th>
 </tr>
 <tr>
 <td class="left">1</td>
 <td class="left">Australia Women</td>
 <td class="left">21</td>
 <td class="left">3603</td>
 <td class="left">172</td>
 </tr>
 <tr>
 <td class="left">2</td>
 <td class="left">England Women</td>
 <td class="left">28</td>
 <td class="left">3342</td>
 <td class="left">119</td>
 </tr>
 <tr>
 <td class="left">3</td>
 <td class="left">South Africa Women</td>
 <td class="left">26</td>
 <td class="left">3098</td>
 <td class="left">119</td>
 </tr>
 <tr>
 <td class="left">4</td>
 <td class="left">India Women</td>
 <td class="left">27</td>
 <td class="left">2820</td>
 <td class="left">104</td>
 </tr>
 <tr>
 <td class="left">5</td>
 <td class="left">New Zealand Women</td>
 <td class="left">25</td>
 <td class="left">2553</td>
 <td class="left">102</td>
 </tr>
 <tr>
 <td class="left">6</td>
 <td class="left">West Indies Women</td>
 <td class="left">27</td>
 <td class="left">2535</td>
 <td class="left">94</td>
 </tr>
 <tr>
 <td class="left">7</td>
 <td class="left">Bangladesh Women</td>
 <td class="left">13</td>
 <td class="left">983</td>
 <td class="left">76</td>
 </tr>
 <tr>
 <td class="left">8</td>
 <td class="left">Thailand Women</td>
 <td class="left">8</td>
 <td class="left">572</td>
 <td class="left">72</td>
 </tr>
 <tr>
 <td class="left">9</td>
 <td class="left">Pakistan Women</td>
 <td class="left">27</td>
 <td class="left">1678</td>
 <td class="left">62</td>
 </tr>
 <tr>
 <td class="left">10</td>
 <td class="left">Sri Lanka Women</td>
 <td class="left">8</td>
 <td class="left">353</td>
 <td class="left">44</td>
 </tr>
 <tr>
 <td class="left">11</td>
 <td class="left">Ireland Women</td>
 <td class="left">14</td>
 <td class="left">548</td>
 <td class="left">39</td>
 </tr>
 <tr>

In [19]:
ranking[0] # printing only first table

<table class="StoryengineTable">
<caption>20 March 2023</caption>
<tr class="head">
<th class="left">Pos</th>
<th class="left">Team</th>
<th class="left">Matches</th>
<th class="left">Points</th>
<th class="left">Rating</th>
</tr>
<tr>
<td class="left">1</td>
<td class="left">Australia</td>
<td class="left">34</td>
<td class="left">4143</td>
<td class="left">122</td>
</tr>
<tr>
<td class="left">2</td>
<td class="left">India</td>
<td class="left">37</td>
<td class="left">4420</td>
<td class="left">119</td>
</tr>
<tr>
<td class="left">3</td>
<td class="left">England</td>
<td class="left">47</td>
<td class="left">5017</td>
<td class="left">107</td>
</tr>
<tr>
<td class="left">4</td>
<td class="left">South Africa</td>
<td class="left">32</td>
<td class="left">3336</td>
<td class="left">104</td>
</tr>
<tr>
<td class="left">5</td>
<td class="left">New Zealand</td>
<td class="left">33</td>
<td class="left">3379</td>
<td class="left">102</td>
</tr>
<tr>
<td class="left">6</td>
<td class="left">Pakistan</td>
<td class="left">30</td>
<td class="left">2638</td>
<td class="left">88</td>
</tr>
<tr>
<td class="left">7</td>
<td class="left">Sri Lanka</td>
<td class="left">29</td>
<td class="left">2429</td>
<td class="left">84</td>
</tr>
<tr>
<td class="left">8</td>
<td class="left">West Indies</td>
<td class="left">34</td>
<td class="left">2571</td>
<td class="left">76</td>
</tr>
<tr>
<td class="left">9</td>
<td class="left">Bangladesh</td>
<td class="left">25</td>
<td class="left">1161</td>
<td class="left">46</td>
</tr>
<tr>
<td class="left">10</td>
<td class="left">Zimbabwe</td>
<td class="left">9</td>
<td class="left">243</td>
<td class="left">27</td>
</tr>
</table>

In [11]:
print(ranking[0].caption.text) # we ant to print caption of first table

20 March 2023

In [21]:
trs = ranking[0].find_all('tr') # all tr in first table
trs

[<tr class="head">
 <th class="left">Pos</th>
 <th class="left">Team</th>
 <th class="left">Matches</th>
 <th class="left">Points</th>
 <th class="left">Rating</th>
 </tr>,
 <tr>
 <td class="left">1</td>
 <td class="left">Australia</td>
 <td class="left">34</td>
 <td class="left">4143</td>
 <td class="left">122</td>
 </tr>,
 <tr>
 <td class="left">2</td>
 <td class="left">India</td>
 <td class="left">37</td>
 <td class="left">4420</td>
 <td class="left">119</td>
 </tr>,
 <tr>
 <td class="left">3</td>
 <td class="left">England</td>
 <td class="left">47</td>
 <td class="left">5017</td>
 <td class="left">107</td>
 </tr>,
 <tr>
 <td class="left">4</td>
 <td class="left">South Africa</td>
 <td class="left">32</td>
 <td class="left">3336</td>
 <td class="left">104</td>
 </tr>,
 <tr>
 <td class="left">5</td>
 <td class="left">New Zealand</td>
 <td class="left">33</td>
 <td class="left">3379</td>
 <td class="left">102</td>
 </tr>,
 <tr>
 <td class="left">6</td>
 <td class="left">Pakistan</td>
 <td class="left">30</td>
 <td class="left">2638</td>
 <td class="left">88</td>
 </tr>,
 <tr>
 <td class="left">7</td>
 <td class="left">Sri Lanka</td>
 <td class="left">29</td>
 <td class="left">2429</td>
 <td class="left">84</td>
 </tr>,
 <tr>
 <td class="left">8</td>
 <td class="left">West Indies</td>
 <td class="left">34</td>
 <td class="left">2571</td>
 <td class="left">76</td>
 </tr>,
 <tr>
 <td class="left">9</td>
 <td class="left">Bangladesh</td>
 <td class="left">25</td>
 <td class="left">1161</td>
 <td class="left">46</td>
 </tr>,
 <tr>
 <td class="left">10</td>
 <td class="left">Zimbabwe</td>
 <td class="left">9</td>
 <td class="left">243</td>
 <td class="left">27</td>
 </tr>]

In [22]:
for row in trs: # printing all rows of trs separately
    print(row)

<tr class="head">
<th class="left">Pos</th>
<th class="left">Team</th>
<th class="left">Matches</th>
<th class="left">Points</th>
<th class="left">Rating</th>
</tr>
<tr>
<td class="left">1</td>
<td class="left">Australia</td>
<td class="left">34</td>
<td class="left">4143</td>
<td class="left">122</td>
</tr>
<tr>
<td class="left">2</td>
<td class="left">India</td>
<td class="left">37</td>
<td class="left">4420</td>
<td class="left">119</td>
</tr>
<tr>
<td class="left">3</td>
<td class="left">England</td>
<td class="left">47</td>
<td class="left">5017</td>
<td class="left">107</td>
</tr>
<tr>
<td class="left">4</td>
<td class="left">South Africa</td>
<td class="left">32</td>
<td class="left">3336</td>
<td class="left">104</td>
</tr>
<tr>
<td class="left">5</td>
<td class="left">New Zealand</td>
<td class="left">33</td>
<td class="left">3379</td>
<td class="left">102</td>
</tr>
<tr>
<td class="left">6</td>
<td class="left">Pakistan</td>
<td class="left">30</td>
<td class="left">2638</td>
<td class="left">88</td>
</tr>
<tr>
<td class="left">7</td>
<td class="left">Sri Lanka</td>
<td class="left">29</td>
<td class="left">2429</td>
<td class="left">84</td>
</tr>
<tr>
<td class="left">8</td>
<td class="left">West Indies</td>
<td class="left">34</td>
<td class="left">2571</td>
<td class="left">76</td>
</tr>
<tr>
<td class="left">9</td>
<td class="left">Bangladesh</td>
<td class="left">25</td>
<td class="left">1161</td>
<td class="left">46</td>
</tr>
<tr>
<td class="left">10</td>
<td class="left">Zimbabwe</td>
<td class="left">9</td>
<td class="left">243</td>
<td class="left">27</td>
</tr>

In [23]:
trs[0] # printing first ranking

<tr class="head">
<th class="left">Pos</th>
<th class="left">Team</th>
<th class="left">Matches</th>
<th class="left">Points</th>
<th class="left">Rating</th>
</tr>

In [25]:
trs[0].find_all('th') # printinh all th in first ranking

[<th class="left">Pos</th>,
 <th class="left">Team</th>,
 <th class="left">Matches</th>,
 <th class="left">Points</th>,
 <th class="left">Rating</th>]

In [27]:
# now we want all text of 'th' for first ranking 
for th in trs[0].find_all('th'):
    print(th.text)

Pos
Team
Matches
Points
Rating

In [29]:
trs[0] # in first row all rows have th

<tr class="head">
<th class="left">Pos</th>
<th class="left">Team</th>
<th class="left">Matches</th>
<th class="left">Points</th>
<th class="left">Rating</th>
</tr>

In [28]:
trs[1]# in second row all rows have td

<tr>
<td class="left">1</td>
<td class="left">Australia</td>
<td class="left">34</td>
<td class="left">4143</td>
<td class="left">122</td>
</tr>

In [30]:
trs[1:] # we check that exclusig first ranking all other rankings have td

[<tr>
 <td class="left">1</td>
 <td class="left">Australia</td>
 <td class="left">34</td>
 <td class="left">4143</td>
 <td class="left">122</td>
 </tr>,
 <tr>
 <td class="left">2</td>
 <td class="left">India</td>
 <td class="left">37</td>
 <td class="left">4420</td>
 <td class="left">119</td>
 </tr>,
 <tr>
 <td class="left">3</td>
 <td class="left">England</td>
 <td class="left">47</td>
 <td class="left">5017</td>
 <td class="left">107</td>
 </tr>,
 <tr>
 <td class="left">4</td>
 <td class="left">South Africa</td>
 <td class="left">32</td>
 <td class="left">3336</td>
 <td class="left">104</td>
 </tr>,
 <tr>
 <td class="left">5</td>
 <td class="left">New Zealand</td>
 <td class="left">33</td>
 <td class="left">3379</td>
 <td class="left">102</td>
 </tr>,
 <tr>
 <td class="left">6</td>
 <td class="left">Pakistan</td>
 <td class="left">30</td>
 <td class="left">2638</td>
 <td class="left">88</td>
 </tr>,
 <tr>
 <td class="left">7</td>
 <td class="left">Sri Lanka</td>
 <td class="left">29</td>
 <td class="left">2429</td>
 <td class="left">84</td>
 </tr>,
 <tr>
 <td class="left">8</td>
 <td class="left">West Indies</td>
 <td class="left">34</td>
 <td class="left">2571</td>
 <td class="left">76</td>
 </tr>,
 <tr>
 <td class="left">9</td>
 <td class="left">Bangladesh</td>
 <td class="left">25</td>
 <td class="left">1161</td>
 <td class="left">46</td>
 </tr>,
 <tr>
 <td class="left">10</td>
 <td class="left">Zimbabwe</td>
 <td class="left">9</td>
 <td class="left">243</td>
 <td class="left">27</td>
 </tr>]

In [31]:
# printing first ranking


#Print ranking for only one format
for th in trs[0].find_all('th'): #Heading row (first row)
        print('{:13}'.format(th.text), end=" ") #====> 13 is characer width mean the gap of two words
print() #Move to next line
for tr in trs[1:]:  #All rows exclusding first row because all rows have td but first row have th so we do separately for first row the above code is for first row  
    for td in tr.find_all('td'): #All columns
        print('{:13}'.format(td.text), end=" ")
    print()

Pos           Team          Matches       Points        Rating
1             Australia     34            4143          122
2             India         37            4420          119
3             England       47            5017          107
4             South Africa  32            3336          104
5             New Zealand   33            3379          102
6             Pakistan      30            2638          88
7             Sri Lanka     29            2429          84
8             West Indies   34            2571          76
9             Bangladesh    25            1161          46
10            Zimbabwe      9             243           27

In [32]:
#Now print rankings for all the format

In [33]:
def print_ranking(trs):
    for th in trs[0].find_all('th'): #Heading row
        print('{:20}'.format(th.text), end=" ")
    print() #Move to next line
    for tr in trs[1:]:  #All rows    
        for td in tr.find_all('td'): #All columns
            print('{:20}'.format(td.text), end=" ")
        print()

In [34]:
for r in ranking: #For all the rankings
    print(r.caption.text)
    print_ranking(r.find_all('tr'))
    print('\n\n\n')

20 March 2023
Pos                  Team                 Matches              Points               Rating
1                    Australia            34                   4143                 122
2                    India                37                   4420                 119
3                    England              47                   5017                 107
4                    South Africa         32                   3336                 104
5                    New Zealand          33                   3379                 102
6                    Pakistan             30                   2638                 88
7                    Sri Lanka            29                   2429                 84
8                    West Indies          34                   2571                 76
9                    Bangladesh           25                   1161                 46
10                   Zimbabwe             9                    243                  27




29 March 2023
Pos                  Team                 Matches              Points               Rating
1                    Australia            35                   3965                 113
2                    India                47                   5294                 113
3                    New Zealand          30                   3367                 112
4                    England              36                   3988                 111
5                    Pakistan             25                   2649                 106
6                    South Africa         29                   2919                 101
7                    Bangladesh           38                   3625                 95
8                    Sri Lanka            35                   3037                 87
9                    West Indies          43                   3105                 72
10                   Afghanistan          20                   1419                 71
11                   Ireland              27                   1384                 51
12                   Scotland             35                   1567                 45
13                   Zimbabwe             31                   1351                 44
14                   Netherlands          24                   749                  31
15                   Nepal                40                   1238                 31
16                   Oman                 30                   919                  31
17                   Namibia              34                   990                  29
18                   USA                  33                   901                  27
19                   UAE                  36                   739                  21
20                   PNG                  40                   181                  5




29 March 2023
Pos                  Team                 Matches              Points               Rating
1                    India                69                   18445                267
2                    England              52                   13555                261
3                    Pakistan             58                   14775                255
4                    South Africa         44                   11170                254
5                    New Zealand          53                   13371                252
6                    Australia            47                   11784                251
7                    West Indies          54                   12855                238
8                    Sri Lanka            53                   12485                236
9                    Bangladesh           56                   12746                228
10                   Afghanistan          36                   7928                 220
11                   Zimbabwe             49                   9597                 196
12                   Ireland              59                   11172                189
13                   UAE                  32                   5898                 184
14                   Namibia              32                   5846                 183
15                   Scotland             24                   4373                 182
16                   Nepal                30                   5387                 180
17                   Netherlands          32                   5668                 177
18                   Oman                 26                   4090                 157
19                   PNG                  24                   3495                 146
20                   Canada               24                   3297                 137
21                   Hong Kong            24                   3205                 134
22                   Qatar                17                   2169                 128
23                   Jersey               23                   2924                 127
24                   Uganda               46                   5648                 123
25                   USA                  16                   1908                 119
26                   Kuwait               22                   2501                 114
27                   Malaysia             37                   4139                 112
28                   Kenya                31                   3272                 106
29                   Bahrain              33                   3435                 104
30                   Singapore            28                   2861                 102
31                   Tanzania             36                   3598                 100
32                   Italy                19                   1818                 96
33                   Saudi Arabia         13                   1234                 95
34                   Bermuda              18                   1671                 93
35                   Germany              34                   2996                 88
36                   Spain                26                   2267                 87
37                   Denmark              21                   1518                 72
38                   Guernsey             17                   1194                 70
39                   Cayman Islands       12                   814                  68
40                   Belgium              20                   1349                 67
41                   Nigeria              29                   1952                 67
42                   Austria              26                   1686                 65
43                   Vanuatu              14                   877                  63
44                   Portugal             11                   644                  59
45                   Romania              24                   1359                 57
46                   Isle of Man          15                   847                  56
47                   Botswana             18                   992                  55
48                   Norway               17                   897                  53
49                   Finland              17                   892                  52
50                   France               9                    470                  52
51                   Malawi               17                   818                  48
52                   Sweden               16                   690                  43
53                   Cook Islands         6                    245                  41
54                   Czech Republic       28                   1137                 41
55                   Argentina            15                   604                  40
56                   Indonesia            7                    265                  38
57                   Switzerland          11                   396                  36
58                   Malta                33                   1179                 36
59                   Ghana                23                   813                  35
60                   Sierra Leone         17                   586                  34
61                   Japan                7                    236                  34
62                   Luxembourg           23                   774                  34
63                   Mozambique           23                   721                  31
64                   Fiji                 10                   304                  30
65                   Bhutan               8                    239                  30
66                   Rwanda               34                   918                  27
67                   Cyprus               11                   283                  26
68                   Bahamas              15                   359                  24
69                   Hungary              16                   358                  22
70                   Panama               10                   222                  22
71                   Belize               6                    132                  22
72                   Serbia               17                   184                  11
73                   Bulgaria             34                   296                  9
74                   Gambia               7                    50                   7
75                   Lesotho              12                   82                   7
76                   Maldives             15                   81                   5
77                   Gibraltar            21                   68                   3
78                   Greece               9                    27                   3
79                   Turkey               6                    0                    0
80                   Thailand             10                   0                    0
81                   Eswatini             18                   0                    0
82                   Seychelles           10                   0                    0
83                   Samoa                11                   0                    0
84                   Estonia              12                   0                    0
85                   Cameroon             13                   0                    0




21 January 2023
Pos                  Team                 Matches              Points               Rating
1                    Australia Women      21                   3603                 172
2                    England Women        28                   3342                 119
3                    South Africa Women   26                   3098                 119
4                    India Women          27                   2820                 104
5                    New Zealand Women    25                   2553                 102
6                    West Indies Women    27                   2535                 94
7                    Bangladesh Women     13                   983                  76
8                    Thailand Women       8                    572                  72
9                    Pakistan Women       27                   1678                 62
10                   Sri Lanka Women      8                    353                  44
11                   Ireland Women        14                   548                  39
12                   Netherlands Women    9                    0                    0
13                   Zimbabwe Women       8                    0                    0




29 March 2023
Pos                  Team                 Matches              Points               Rating
1                    Australia Women      29                   8750                 302
2                    England Women        35                   9886                 282
3                    New Zealand Women    28                   7511                 268
4                    India Women          46                   12186                265
5                    South Africa Women   27                   6831                 253
6                    West Indies Women    27                   6157                 228
7                    Pakistan Women       30                   6592                 220
8                    Sri Lanka Women      26                   5548                 213
9                    Bangladesh Women     26                   4907                 189
10                   Ireland Women        26                   4629                 178
11                   Zimbabwe Women       20                   3239                 162
12                   PNG Women            15                   2396                 160
13                   Thailand Women       22                   3557                 162
14                   Scotland Women       15                   2142                 143
15                   UAE Women            31                   4093                 132
16                   Tanzania Women       19                   2124                 112
17                   Nepal Women          19                   2093                 110
18                   Namibia Women        21                   2189                 104
19                   Indonesia Women      8                    826                  103
20                   Uganda Women         29                   2910                 100
21                   Netherlands Women    13                   1302                 100
22                   Kenya Women          25                   2171                 87
23                   Hong Kong Women      18                   1523                 85
24                   Jersey Women         6                    458                  76
25                   USA Women            14                   971                  69
26                   Rwanda Women         21                   1270                 60
27                   Italy Women          12                   721                  60
28                   Malaysia Women       24                   1403                 58
29                   Nigeria Women        20                   1086                 54
30                   Sweden Women         10                   495                  50
31                   Germany Women        20                   952                  47
32                   Brazil Women         19                   900                  47
33                   Canada Women         6                    277                  46
34                   Belize Women         3                    135                  45
35                   Vanuatu Women        10                   444                  44
36                   Spain Women          8                    256                  32
37                   Mozambique Women     12                   328                  27
38                   France Women         9                    214                  24
39                   Sierra Leone Women   10                   236                  24
40                   Botswana Women       15                   345                  23
41                   Bhutan Women         9                    207                  23
42                   Oman Women           13                   289                  22
43                   Samoa Women          10                   205                  21
44                   Singapore Women      18                   367                  20
45                   Malawi Women         4                    71                   18
46                   Kuwait Women         16                   278                  17
47                   Bahrain Women        8                    138                  17
48                   Romania Women        7                    105                  15
49                   Qatar Women          21                   245                  12
50                   Costa Rica Women     3                    34                   11
51                   Argentina Women      12                   95                   8
52                   Austria Women        16                   99                   6
53                   Cambodia Women       11                   65                   6
54                   Phlilippines Women   8                    42                   5
55                   Fiji Women           10                   28                   3
56                   Eswatini Women       9                    0                    0
57                   Norway Women         9                    0                    0
58                   Peru Women           5                    0                    0
59                   Ghana Women          7                    0                    0

In [35]:
#Now we will print the format details as well
format=html_soup.find_all('div' , class_="ciPhotoContainer")[0].find_all('h3')

In [36]:
format

[<h3>ICC Test Rankings</h3>,
 <h3>ICC ODI Rankings</h3>,
 <h3>ICC Twenty20 Rankings</h3>,
 <h3>ICC Women's ODI Team Rankings</h3>,
 <h3>ICC Women's T20 Team Rankings</h3>]

In [37]:
i=0
for r in ranking: #For all the rankings
    print(r.caption.text)
    print(format[i].text)
    print_ranking(r.find_all('tr'))
    print('\n\n\n')
    i+=1

20 March 2023
ICC Test Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia            34                   4143                 122
2                    India                37                   4420                 119
3                    England              47                   5017                 107
4                    South Africa         32                   3336                 104
5                    New Zealand          33                   3379                 102
6                    Pakistan             30                   2638                 88
7                    Sri Lanka            29                   2429                 84
8                    West Indies          34                   2571                 76
9                    Bangladesh           25                   1161                 46
10                   Zimbabwe             9                    243                  27




29 March 2023
ICC ODI Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia            35                   3965                 113
2                    India                47                   5294                 113
3                    New Zealand          30                   3367                 112
4                    England              36                   3988                 111
5                    Pakistan             25                   2649                 106
6                    South Africa         29                   2919                 101
7                    Bangladesh           38                   3625                 95
8                    Sri Lanka            35                   3037                 87
9                    West Indies          43                   3105                 72
10                   Afghanistan          20                   1419                 71
11                   Ireland              27                   1384                 51
12                   Scotland             35                   1567                 45
13                   Zimbabwe             31                   1351                 44
14                   Netherlands          24                   749                  31
15                   Nepal                40                   1238                 31
16                   Oman                 30                   919                  31
17                   Namibia              34                   990                  29
18                   USA                  33                   901                  27
19                   UAE                  36                   739                  21
20                   PNG                  40                   181                  5




29 March 2023
ICC Twenty20 Rankings
Pos                  Team                 Matches              Points               Rating
1                    India                69                   18445                267
2                    England              52                   13555                261
3                    Pakistan             58                   14775                255
4                    South Africa         44                   11170                254
5                    New Zealand          53                   13371                252
6                    Australia            47                   11784                251
7                    West Indies          54                   12855                238
8                    Sri Lanka            53                   12485                236
9                    Bangladesh           56                   12746                228
10                   Afghanistan          36                   7928                 220
11                   Zimbabwe             49                   9597                 196
12                   Ireland              59                   11172                189
13                   UAE                  32                   5898                 184
14                   Namibia              32                   5846                 183
15                   Scotland             24                   4373                 182
16                   Nepal                30                   5387                 180
17                   Netherlands          32                   5668                 177
18                   Oman                 26                   4090                 157
19                   PNG                  24                   3495                 146
20                   Canada               24                   3297                 137
21                   Hong Kong            24                   3205                 134
22                   Qatar                17                   2169                 128
23                   Jersey               23                   2924                 127
24                   Uganda               46                   5648                 123
25                   USA                  16                   1908                 119
26                   Kuwait               22                   2501                 114
27                   Malaysia             37                   4139                 112
28                   Kenya                31                   3272                 106
29                   Bahrain              33                   3435                 104
30                   Singapore            28                   2861                 102
31                   Tanzania             36                   3598                 100
32                   Italy                19                   1818                 96
33                   Saudi Arabia         13                   1234                 95
34                   Bermuda              18                   1671                 93
35                   Germany              34                   2996                 88
36                   Spain                26                   2267                 87
37                   Denmark              21                   1518                 72
38                   Guernsey             17                   1194                 70
39                   Cayman Islands       12                   814                  68
40                   Belgium              20                   1349                 67
41                   Nigeria              29                   1952                 67
42                   Austria              26                   1686                 65
43                   Vanuatu              14                   877                  63
44                   Portugal             11                   644                  59
45                   Romania              24                   1359                 57
46                   Isle of Man          15                   847                  56
47                   Botswana             18                   992                  55
48                   Norway               17                   897                  53
49                   Finland              17                   892                  52
50                   France               9                    470                  52
51                   Malawi               17                   818                  48
52                   Sweden               16                   690                  43
53                   Cook Islands         6                    245                  41
54                   Czech Republic       28                   1137                 41
55                   Argentina            15                   604                  40
56                   Indonesia            7                    265                  38
57                   Switzerland          11                   396                  36
58                   Malta                33                   1179                 36
59                   Ghana                23                   813                  35
60                   Sierra Leone         17                   586                  34
61                   Japan                7                    236                  34
62                   Luxembourg           23                   774                  34
63                   Mozambique           23                   721                  31
64                   Fiji                 10                   304                  30
65                   Bhutan               8                    239                  30
66                   Rwanda               34                   918                  27
67                   Cyprus               11                   283                  26
68                   Bahamas              15                   359                  24
69                   Hungary              16                   358                  22
70                   Panama               10                   222                  22
71                   Belize               6                    132                  22
72                   Serbia               17                   184                  11
73                   Bulgaria             34                   296                  9
74                   Gambia               7                    50                   7
75                   Lesotho              12                   82                   7
76                   Maldives             15                   81                   5
77                   Gibraltar            21                   68                   3
78                   Greece               9                    27                   3
79                   Turkey               6                    0                    0
80                   Thailand             10                   0                    0
81                   Eswatini             18                   0                    0
82                   Seychelles           10                   0                    0
83                   Samoa                11                   0                    0
84                   Estonia              12                   0                    0
85                   Cameroon             13                   0                    0




21 January 2023
ICC Women's ODI Team Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia Women      21                   3603                 172
2                    England Women        28                   3342                 119
3                    South Africa Women   26                   3098                 119
4                    India Women          27                   2820                 104
5                    New Zealand Women    25                   2553                 102
6                    West Indies Women    27                   2535                 94
7                    Bangladesh Women     13                   983                  76
8                    Thailand Women       8                    572                  72
9                    Pakistan Women       27                   1678                 62
10                   Sri Lanka Women      8                    353                  44
11                   Ireland Women        14                   548                  39
12                   Netherlands Women    9                    0                    0
13                   Zimbabwe Women       8                    0                    0




29 March 2023
ICC Women's T20 Team Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia Women      29                   8750                 302
2                    England Women        35                   9886                 282
3                    New Zealand Women    28                   7511                 268
4                    India Women          46                   12186                265
5                    South Africa Women   27                   6831                 253
6                    West Indies Women    27                   6157                 228
7                    Pakistan Women       30                   6592                 220
8                    Sri Lanka Women      26                   5548                 213
9                    Bangladesh Women     26                   4907                 189
10                   Ireland Women        26                   4629                 178
11                   Zimbabwe Women       20                   3239                 162
12                   PNG Women            15                   2396                 160
13                   Thailand Women       22                   3557                 162
14                   Scotland Women       15                   2142                 143
15                   UAE Women            31                   4093                 132
16                   Tanzania Women       19                   2124                 112
17                   Nepal Women          19                   2093                 110
18                   Namibia Women        21                   2189                 104
19                   Indonesia Women      8                    826                  103
20                   Uganda Women         29                   2910                 100
21                   Netherlands Women    13                   1302                 100
22                   Kenya Women          25                   2171                 87
23                   Hong Kong Women      18                   1523                 85
24                   Jersey Women         6                    458                  76
25                   USA Women            14                   971                  69
26                   Rwanda Women         21                   1270                 60
27                   Italy Women          12                   721                  60
28                   Malaysia Women       24                   1403                 58
29                   Nigeria Women        20                   1086                 54
30                   Sweden Women         10                   495                  50
31                   Germany Women        20                   952                  47
32                   Brazil Women         19                   900                  47
33                   Canada Women         6                    277                  46
34                   Belize Women         3                    135                  45
35                   Vanuatu Women        10                   444                  44
36                   Spain Women          8                    256                  32
37                   Mozambique Women     12                   328                  27
38                   France Women         9                    214                  24
39                   Sierra Leone Women   10                   236                  24
40                   Botswana Women       15                   345                  23
41                   Bhutan Women         9                    207                  23
42                   Oman Women           13                   289                  22
43                   Samoa Women          10                   205                  21
44                   Singapore Women      18                   367                  20
45                   Malawi Women         4                    71                   18
46                   Kuwait Women         16                   278                  17
47                   Bahrain Women        8                    138                  17
48                   Romania Women        7                    105                  15
49                   Qatar Women          21                   245                  12
50                   Costa Rica Women     3                    34                   11
51                   Argentina Women      12                   95                   8
52                   Austria Women        16                   99                   6
53                   Cambodia Women       11                   65                   6
54                   Phlilippines Women   8                    42                   5
55                   Fiji Women           10                   28                   3
56                   Eswatini Women       9                    0                    0
57                   Norway Women         9                    0                    0
58                   Peru Women           5                    0                    0
59                   Ghana Women          7                    0                    0

In [63]:
#Let's do the same thing with enumerate
for i,r in enumerate(ranking): #For all the rankings
    print(r.caption.text)
    print(format[i].text)
    print_ranking(r.find_all('tr'))
    print('\n\n\n')

08 January 2023
ICC Test Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia            29                   3668                 126
2                    India                32                   3690                 115
3                    England              47                   5017                 107
4                    South Africa         29                   2952                 102
5                    New Zealand          30                   2965                 99
6                    Pakistan             30                   2638                 88
7                    Sri Lanka            26                   2282                 88
8                    West Indies          28                   2198                 79
9                    Bangladesh           25                   1161                 46
10                   Zimbabwe             6                    148                  25




01 February 2023
ICC ODI Rankings
Pos                  Team                 Matches              Points               Rating
1                    India                44                   5010                 114
2                    Australia            32                   3572                 112
3                    New Zealand          29                   3229                 111
4                    England              33                   3656                 111
5                    Pakistan             25                   2649                 106
6                    South Africa         27                   2775                 103
7                    Bangladesh           33                   3129                 95
8                    Sri Lanka            34                   2976                 88
9                    Afghanistan          20                   1419                 71
10                   West Indies          41                   2902                 71
11                   Ireland              25                   1300                 52
12                   Scotland             31                   1459                 47
13                   Zimbabwe             28                   1201                 43
14                   Namibia              26                   971                  37
15                   Netherlands          21                   673                  32
16                   Oman                 30                   919                  31
17                   UAE                  25                   693                  28
18                   USA                  31                   821                  26
19                   Nepal                28                   456                  16
20                   PNG                  30                   128                  4




01 February 2023
ICC Twenty20 Rankings
Pos                  Team                 Matches              Points               Rating
1                    India                69                   18445                267
2                    England              49                   13029                266
3                    Pakistan             55                   14168                258
4                    South Africa         41                   10510                256
5                    New Zealand          53                   13371                252
6                    Australia            47                   11784                251
7                    West Indies          51                   12039                236
8                    Sri Lanka            53                   12485                236
9                    Bangladesh           51                   11328                222
10                   Afghanistan          30                   6512                 217
11                   Zimbabwe             49                   9597                 196
12                   Ireland              57                   10818                190
13                   UAE                  29                   5298                 183
14                   Namibia              32                   5846                 183
15                   Scotland             24                   4373                 182
16                   Nepal                30                   5387                 180
17                   Netherlands          32                   5668                 177
18                   Oman                 26                   4090                 157
19                   PNG                  24                   3495                 146
20                   Canada               24                   3297                 137
21                   Hong Kong            20                   2555                 128
22                   Qatar                17                   2169                 128
23                   Jersey               23                   2924                 127
24                   Uganda               46                   5648                 123
25                   Kuwait               18                   2153                 120
26                   USA                  16                   1908                 119
27                   Malaysia             33                   3651                 111
28                   Bahrain              29                   3068                 106
29                   Kenya                31                   3272                 106
30                   Singapore            28                   2861                 102
31                   Tanzania             36                   3598                 100
32                   Italy                19                   1818                 96
33                   Saudi Arabia         13                   1234                 95
34                   Germany              34                   2996                 88
35                   Bermuda              12                   1053                 88
36                   Spain                21                   1705                 81
37                   Denmark              21                   1518                 72
38                   Guernsey             17                   1194                 70
39                   Isle of Man          10                   678                  68
40                   Belgium              20                   1349                 67
41                   Nigeria              29                   1952                 67
42                   Cayman Islands       8                    529                  66
43                   Austria              26                   1686                 65
44                   Vanuatu              11                   645                  59
45                   Portugal             11                   644                  59
46                   Romania              24                   1359                 57
47                   Botswana             18                   992                  55
48                   Norway               17                   897                  53
49                   Finland              17                   892                  52
50                   France               9                    470                  52
51                   Argentina            9                    435                  48
52                   Malawi               17                   818                  48
53                   Sweden               16                   690                  43
54                   Cook Islands         6                    245                  41
55                   Czech Republic       28                   1137                 41
56                   Indonesia            7                    265                  38
57                   Switzerland          11                   396                  36
58                   Malta                33                   1179                 36
59                   Ghana                23                   813                  35
60                   Sierra Leone         17                   586                  34
61                   Japan                7                    236                  34
62                   Luxembourg           23                   774                  34
63                   Mozambique           23                   721                  31
64                   Bhutan               8                    239                  30
65                   Fiji                 6                    177                  30
66                   Rwanda               34                   918                  27
67                   Cyprus               11                   283                  26
68                   Bahamas              11                   260                  24
69                   Hungary              16                   358                  22
70                   Belize               6                    132                  22
71                   Panama               6                    125                  21
72                   Serbia               17                   184                  11
73                   Bulgaria             34                   296                  9
74                   Gambia               7                    50                   7
75                   Lesotho              12                   82                   7
76                   Maldives             15                   81                   5
77                   Samoa                8                    42                   5
78                   Gibraltar            21                   68                   3
79                   Greece               9                    27                   3
80                   Turkey               6                    0                    0
81                   Thailand             10                   0                    0
82                   Eswatini             18                   0                    0
83                   Seychelles           10                   0                    0
84                   Estonia              12                   0                    0
85                   Cameroon             13                   0                    0




21 January 2023
ICC Women's ODI Team Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia Women      21                   3603                 172
2                    England Women        28                   3342                 119
3                    South Africa Women   26                   3098                 119
4                    India Women          27                   2820                 104
5                    New Zealand Women    25                   2553                 102
6                    West Indies Women    27                   2535                 94
7                    Bangladesh Women     13                   983                  76
8                    Thailand Women       8                    572                  72
9                    Pakistan Women       27                   1678                 62
10                   Sri Lanka Women      8                    353                  44
11                   Ireland Women        14                   548                  39
12                   Netherlands Women    9                    0                    0
13                   Zimbabwe Women       8                    0                    0




02 February 2023
ICC Women's T20 Team Rankings
Pos                  Team                 Matches              Points               Rating
1                    Australia Women      24                   7182                 299
2                    England Women        30                   8489                 283
3                    New Zealand Women    24                   6509                 271
4                    India Women          41                   10875                265
5                    South Africa Women   21                   5272                 251
6                    West Indies Women    23                   5217                 227
7                    Pakistan Women       26                   5763                 222
8                    Sri Lanka Women      23                   4804                 209
9                    Bangladesh Women     22                   4205                 191
10                   Ireland Women        22                   3953                 180
11                   Zimbabwe Women       20                   3239                 162
12                   Thailand Women       22                   3557                 162
13                   PNG Women            10                   1558                 156
14                   Scotland Women       15                   2142                 143
15                   UAE Women            31                   4093                 132
16                   Tanzania Women       19                   2124                 112
17                   Nepal Women          19                   2093                 110
18                   Namibia Women        21                   2189                 104
19                   Indonesia Women      8                    826                  103
20                   Uganda Women         29                   2910                 100
21                   Netherlands Women    13                   1302                 100
22                   Kenya Women          25                   2171                 87
23                   Hong Kong Women      18                   1523                 85
24                   Jersey Women         6                    458                  76
25                   USA Women            14                   971                  69
26                   Italy Women          12                   721                  60
27                   Rwanda Women         19                   1126                 59
28                   Malaysia Women       24                   1403                 58
29                   Nigeria Women        18                   947                  53
30                   Sweden Women         10                   495                  50
31                   Germany Women        20                   952                  47
32                   Brazil Women         19                   900                  47
33                   Canada Women         6                    277                  46
34                   Belize Women         3                    135                  45
35                   Cambodia Women       6                    261                  44
36                   Spain Women          8                    256                  32
37                   Mozambique Women     12                   328                  27
38                   Sierra Leone Women   7                    173                  25
39                   France Women         9                    214                  24
40                   Botswana Women       15                   345                  23
41                   Bhutan Women         9                    207                  23
42                   Oman Women           13                   289                  22
43                   Malawi Women         4                    71                   18
44                   Kuwait Women         16                   278                  17
45                   Bahrain Women        8                    138                  17
46                   Romania Women        7                    105                  15
47                   Qatar Women          21                   245                  12
48                   Costa Rica Women     3                    34                   11
49                   Argentina Women      12                   95                   8
50                   Austria Women        16                   99                   6
51                   Phlilippines Women   8                    42                   5
52                   Eswatini Women       9                    0                    0
53                   Singapore Women      13                   0                    0
54                   Norway Women         9                    0                    0
55                   Peru Women           5                    0                    0

In [43]:
def csv_ranking(trs):
    data = ""
    for th in trs[0].find_all('th'): #Heading row
        data+=th.text+","
    data = data[:-1] #Remove last comma
    data+='\n' #Move to next line
    for tr in trs[1:]:  #All rows    
        for td in tr.find_all('td'): #All columns
            data+=td.text+","
        data = data[:-1]
        data+='\n'
    return data

In [44]:
r=ranking[0]
data = csv_ranking(r.find_all('tr'))
print(data)

Pos,Team,Matches,Points,Rating
1,Australia,34,4143,122
2,India,37,4420,119
3,England,47,5017,107
4,South Africa,32,3336,104
5,New Zealand,33,3379,102
6,Pakistan,30,2638,88
7,Sri Lanka,29,2429,84
8,West Indies,34,2571,76
9,Bangladesh,25,1161,46
10,Zimbabwe,9,243,27

In [48]:
r=ranking[0]
data = csv_ranking(r.find_all('tr'))
file = format[0].text # format[0] is file name which is ICC Test Rankings
data = csv_ranking(r.find_all('tr'))
with open(file+".csv","w") as f:
    f.writelines(data)

In [50]:
# files for all formats
for i,r in enumerate(ranking):
    file = format[i].text
    data = csv_ranking(r.find_all('tr'))
    with open(file+".csv","w") as f:
        f.writelines(data)

In [51]:
import pandas as pd

In [52]:
frame = pd.read_csv('ICC Twenty20 Rankings.csv')

In [53]:
frame

    Pos          Team  Matches  Points  Rating
0     1         India       69   18445     267
1     2       England       52   13555     261
2     3      Pakistan       58   14775     255
3     4  South Africa       44   11170     254
4     5   New Zealand       53   13371     252
..  ...           ...      ...     ...     ...
80   81      Eswatini       18       0       0
81   82    Seychelles       10       0       0
82   83         Samoa       11       0       0
83   84       Estonia       12       0       0
84   85      Cameroon       13       0       0

[85 rows x 5 columns]